# coastline_overlay.gd — Renders coastline LineStrip meshes at multiple LODs.
# Loads coastlines.json (generated by coastline_gen.py).
# Selects LOD based on camera distance.
extends Node3D

const COASTLINE_OFFSET_FACTOR := 1.004
const DATA_PATH := "res://../data/output/coastlines.json"

var _lod_meshes: Dictionary = {}  # "fine"|"medium"|"coarse" → MeshInstance3D
var _current_lod: String = "medium"


func _ready() -> void:
	_load_and_create_meshes()


func _load_and_create_meshes() -> void:
	if not FileAccess.file_exists(DATA_PATH):
		print("Coastline data not found: %s" % DATA_PATH)
		return

	var file: FileAccess = FileAccess.open(DATA_PATH, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()

	var json: JSON = JSON.new()
	if json.parse(json_text) != OK:
		print("Failed to parse coastline JSON")
		return

	var data: Dictionary = json.get_data()
	for lod_name in data:
		var mesh: MeshInstance3D = _create_line_mesh(data[lod_name], lod_name)
		_lod_meshes[lod_name] = mesh
		mesh.visible = (lod_name == _current_lod)
		add_child(mesh)

	print("Coastline overlay loaded: %d LODs" % _lod_meshes.size())


func _create_line_mesh(rings: Array, lod_name: String) -> MeshInstance3D:
	var st: SurfaceTool = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_LINES)

	for ring in rings:
		# ring is a flat array: [x0, y0, z0, x1, y1, z1, ...]
		var count: int = ring.size() / 3
		if count < 2:
			continue

		for i in range(count - 1):
			var idx0 := i * 3
			var idx1 := (i + 1) * 3
			var v0: Vector3 = Vector3(ring[idx0], ring[idx0 + 1], ring[idx0 + 2])
			var v1: Vector3 = Vector3(ring[idx1], ring[idx1 + 1], ring[idx1 + 2])
			st.add_vertex(v0)
			st.add_vertex(v1)

		# Close the ring
		var last_idx := (count - 1) * 3
		var v_last: Vector3 = Vector3(ring[last_idx], ring[last_idx + 1], ring[last_idx + 2])
		var v_first: Vector3 = Vector3(ring[0], ring[1], ring[2])
		st.add_vertex(v_last)
		st.add_vertex(v_first)

	var mesh: ArrayMesh = st.commit()
	if not mesh:
		return MeshInstance3D.new()

	var mi: MeshInstance3D = MeshInstance3D.new()
	mi.name = "Coastline_" + lod_name.to_upper()
	mi.mesh = mesh

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.08, 0.15, 0.35)  # Dark navy coastline
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	mat.flags_unshaded = true
	mat.no_depth_test = true
	mi.material_override = mat

	return mi


## Select LOD based on camera distance (in km from Earth center)
func set_lod_by_distance(distance_km: float) -> void:
	var new_lod: String
	if distance_km < 10000.0:
		new_lod = "fine"
	elif distance_km < 25000.0:
		new_lod = "medium"
	else:
		new_lod = "coarse"

	if new_lod != _current_lod:
		for lod_name in _lod_meshes:
			_lod_meshes[lod_name].visible = (lod_name == new_lod)
		_current_lod = new_lod
