# river_overlay.gd — Renders rivers as LineStrips along cell edges.
# Loads rivers.json (generated by river_gen.py).
# Rivers follow cell edges at the grid resolution — each edge is a
# line segment between two grid vertices on the same band or crossing bands.
extends Node3D

const RIVER_OFFSET_FACTOR := 1.005
const EARTH_RADIUS_KM := 6371.0
const DATA_PATH := "res://../data/output/grid_10km/rivers.json"

# Lazy-loaded band structure for vertex computation
var _band_structure: Dictionary = {}


func _ready() -> void:
	# Defer loading until band structure is available from earth_display
	pass


## Initialize with band structure from earth_display, then create mesh
func initialize(band_structure: Dictionary) -> void:
	_band_structure = band_structure
	_load_and_create_mesh()


func _load_and_create_mesh() -> void:
	if _band_structure.is_empty():
		print("River overlay: no band structure provided")
		return

	if not FileAccess.file_exists(DATA_PATH):
		print("River data not found: %s" % DATA_PATH)
		return

	var file: FileAccess = FileAccess.open(DATA_PATH, FileAccess.READ)
	var json_text: String = file.get_as_text()
	file.close()

	var json: JSON = JSON.new()
	if json.parse(json_text) != OK:
		print("Failed to parse rivers JSON")
		return

	var rivers_data: Dictionary = json.get_data()
	var total_bands: int = _band_structure["total_bands"]
	var band_segs: Array = _band_structure["band_segs"]
	var radius: float = EARTH_RADIUS_KM * RIVER_OFFSET_FACTOR
	var vertex_count: int = 0

	var st: SurfaceTool = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_LINES)

	for river_name in rivers_data:
		var river = rivers_data[river_name]
		var edges = river.get("edges", [])
		if edges.is_empty():
			continue

		var prev_end: Vector3 = Vector3.ZERO
		var first_segment: bool = true

		for edge in edges:
			var band: int = edge.get("band", 0)
			var seg: int = edge.get("seg", 0)
			var direction: String = edge.get("dir", "E")

			# Compute the two endpoints of this cell edge
			var v1: Vector3 = _grid_vertex_position(band, seg, radius, total_bands, band_segs)
			var v2: Vector3

			if direction == "N":
				# Edge goes north: from (band, seg) to (band+1, mapped_seg)
				var next_seg: int = _map_segment(seg, band, band + 1, band_segs)
				v2 = _grid_vertex_position(band + 1, next_seg, radius, total_bands, band_segs)
			else:
				# Edge goes east: from (band, seg) to (band, seg+1)
				v2 = _grid_vertex_position(band, (seg + 1) % band_segs[band], radius, total_bands, band_segs)

			st.add_vertex(v1)
			st.add_vertex(v2)

			vertex_count += 2

	var mesh: ArrayMesh = st.commit()
	if not mesh:
		print("River mesh: no geometry generated")
		return

	var mi: MeshInstance3D = MeshInstance3D.new()
	mi.name = "Rivers"
	mi.mesh = mesh

	var mat: StandardMaterial3D = StandardMaterial3D.new()
	mat.albedo_color = Color(0.15, 0.35, 0.65, 0.85)  # River blue, slightly transparent
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	mat.flags_unshaded = true
	mat.no_depth_test = true
	mi.material_override = mat

	add_child(mi)
	print("River overlay loaded: %d rivers, %d vertices" % [rivers_data.size(), vertex_count])


func _grid_vertex_position(band: int, seg: int, radius: float, total_bands: int, band_segs: Array) -> Vector3:
	var lat: float = -PI * 0.5 + PI * float(band) / float(total_bands)
	var segs_at_band: int = band_segs[band] if band < band_segs.size() else 4
	if segs_at_band <= 0:
		segs_at_band = 4
	var lon: float = TAU * float(seg % segs_at_band) / float(segs_at_band)

	return Vector3(
		radius * cos(lat) * cos(lon),
		radius * sin(lat),
		radius * cos(lat) * sin(lon),
	)


func _map_segment(seg: int, from_band: int, to_band: int, band_segs: Array) -> int:
	var from_segs: int = band_segs[from_band] if from_band < band_segs.size() else 4
	var to_segs: int = band_segs[to_band] if to_band < band_segs.size() else 4
	if from_segs <= 0 or to_segs <= 0:
		return 0
	return int(float(seg) * float(to_segs) / float(from_segs))
